---
title: "Homework 1 - Data Analytics"
author: "Costanza Colauzzi, Gabriele Granzotto, Davide Zorzetto"
date: "2023-05-15"
output: html_document
---

```{r}
insurance <- read.csv("insurance.csv")
library(lattice)
```

```{r}
sex <- prop.table(table(insurance$sex))
children <- prop.table(table(insurance$children))
smoker <- prop.table(table(insurance$smoker))
region <- prop.table(table(insurance$region))
opar = par(lwd = 2)
barplot(sex, main="Sex in Insurance", col=c(6,4), border=c("darkgrey", "red")) 
barplot(children, main="Children in Insurance", col=7:2, border=c("red", "darkgrey", "darkgrey", "darkgrey", "darkgrey", "darkgrey"))
barplot(smoker, main="Smoker in Insurance", col=c("yellow", "black"), border=c("red", "darkgrey"))
barplot(region, main="Region in Insurance", col=2:5, border=c("darkgrey","darkgrey","red", "darkgrey"))
```

```{r}
insurance$new.children[insurance$children == 0] <- "0"
insurance$new.children[insurance$children == 1] <- "1"
insurance$new.children[insurance$children == 2] <- "2"
insurance$new.children[insurance$children >= 3] <- "3+"
boxplot(insurance$charges~insurance$new.children, main="Boxplot Charges/Children", xlab="Children", ylab="Charges", col="yellow", border="darkblue")
means <- tapply(insurance$charges, insurance$new.children, mean)
segments(x0=(1:4)-0.4, x1=(1:4)+0.4, y0=means, y1=means, col="red", lwd=2.5)

```

```{r}

insurance$catbmi <- cut(insurance$bmi, breaks = c(0, 18.5, 25, 30, max(insurance$bmi) + 1), labels = c("Underweight", "Normal", "Overweight", "Obese"))

           histogram(~ charges | catbmi, data = insurance, layout = c(1, 4),
                        breaks = (0:6) * max(insurance$charges + 1) / 6, aspect = 0.2, type = "density",
                        panel = function(x, ...) {
                          panel.histogram(x, ..., col="orange")
                          panel.densityplot(x, col = "darkblue", lwd=2, ...)
                        },
           key=list(space="right",
         lines=list(col=c("orange","darkblue"), lwd=2),
         text=list(c("Histogram"," Density")))
)
```

```{r}
prop.sex.bmi <- prop.table(table(insurance$sex,insurance$catbmi), 1)
barplot(prop.sex.bmi, beside=T)
prop.diff <- prop.sex.bmi[1,] - prop.sex.bmi[2,]
barplot(prop.diff, ylim=c(-0.05, 0.05))

```


